repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff-format
        args: [--check]
        files: ^server/
      - id: ruff
        files: ^server/

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier --check
        language: system
        files: ^client/src/
        types_or: [ts, tsx, css]
      - id: eslint
        name: eslint
        entry: npx eslint
        language: system
        files: ^client/src/
        types_or: [ts, tsx]
